name: home_decoration_marketplace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

 
  # example:
  fonts:
    - family: Extrag
      fonts:
        - asset: assets/fonts/Extrag_Light.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf